---
title: "Selenium habitat model - full dataset, scaled"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r}
library(here)
library(funk)
library(knitr)
library(rethinking)
library(tidyverse); theme_set(theme_sleek())
library(tidybayes)

## load all data frames
source('scripts/cleaning/master_data_load.R')
load(file = 'data/aaron_global_posteriors_update.Rdata')
nut='Se'
```

```{r}

focal<-stir.sub %>% filter(nutrient == nut) %>%
		select(nutrient, value, fish_id, units, species, family, 
					mass_kg, Lmax_prop, trophic_level, Lmax, K, tm, Feeding_path, habitat, site) %>%
      mutate(habitat_dummy = ifelse(habitat == 'Coral', 0, 1)) %>%
      mutate(Lmax = log(Lmax), K = log(K))

## drop outliers
outlier.lims<-2*sd(focal$value) + mean(focal$value)
focal<-focal %>% filter(value <= outlier.lims)

## drop any species with fewer than 3 individuals
# subs<-aggregate(fish_id ~ species, focal, uniques)
# sp<-unique(subs$species[subs$fish_id > 2])
# focal<-focal %>% filter(species %in% sp) %>% droplevels()
print(paste0('Fitting model to ',dim(focal)[1], ' samples of ', uniques(focal$species), ' species'))
```

```{r}
## prepare data and y histogram

## standardize exp. covariates, mean = 0
focal<-scaler(focal, 
				ID = c('nutrient','value', 'fish_id', 'units', 'species', 'family','habitat', 'habitat_dummy', 'site'), cats=TRUE) 

## check cor between preds
pairs2(focal[,unlist(lapply(focal, is.numeric)) ], lower.panel=panel.cor, upper.panel=panel.smooth2)

print('Priors are:')
print(posts %>% filter(nut == nut) %>% select(nut,covariate, post, sd)) %>% mutate(post = round(post,3), sd = round(sd,3))

focal$logvalue<-log(focal$value)
focal$benthic_pelagic_dummy<-focal$benthic.pelagic.dummy
focal$site<-as.factor(focal$site)
focal$species<-as.factor(focal$species)
focal$family<-as.factor(focal$family)

par(mfrow=c(1,2))
hist(focal$value, main = nut, xlab=paste(nut))
hist(focal$logvalue, main = nut, xlab=paste('log', nut))

focal.fit<-focal %>% select(value, trophic_level, Lmax, K, tm, benthic_pelagic_dummy, habitat_dummy, species, family, site)
```

```{r} 
# fit model

nt_m<-ulam(
        alist(
          value ~ dgamma2(mu, scale),
          # trait fixed effects
          log(mu) <- a + a_sp[species] + B3*trophic_level + B4*Lmax + 
                B5*K + B6*tm + B7*benthic_pelagic_dummy + (B8 + B8_sp[species])*habitat_dummy + # fixed
          			X1[site]*sigma_site + X2[family]*sigma_fam, 	# random site effect
          
          # adaptive priors - non-centered
          # transpars> matrix[species,2]:B8_sp <-
          #         compose_noncentered(sigma_species, L_Rho, z_species),
          # matrix[2, species]:z_species ~ normal(0, 1),
          c(a_sp, B8_sp)[species] ~ multi_normal(0, Rho, sigma_species),

          # fixed priors
          a ~ dnorm(-0.061, 1.042),
          B3 ~ dnorm(-0.083, 0.248),
    		  B4 ~ dnorm(0.441, 0.192),
    		  B5 ~ dnorm(-0.434, 0.404),
    		  B6 ~ dnorm(-0.352, 0.278),
    		  B7 ~ dnorm(0.524, 0.278),
    		  B8 ~ dnorm(0, 1),
    		  X1[site] ~ dnorm(0, 1),
    		  X2[family] ~ dnorm(0, 1),
          # vector[2]:sigma_species ~ dexp(1),
          c(sigma_site, sigma_fam) ~ dexp(2),
    		  sigma_species ~ dexp(2),
          scale ~ dexp(2),
    		  Rho ~ lkj_corr(3)
          # cholesky_factor_corr[2]:L_Rho ~ lkj_corr_cholesky(2),
          
          # compute ordinary correlation matrixes from Cholesky factors
          # gq> matrix[2,2]:Rho_species<<-multiply_lower_tri_self_transpose(L_Rho)
        ),
        data=focal.fit, iter=5000, warmup=1500, chains=3, cores = 4, control=list(adapt_delta=0.99), message=FALSE)

# load(paste0('results/final/',	 nut, '_scaled_habitat', '.Rdata'))
# nt_m<-output[[1]]
```
#### Divergence

```{r}
d<-divergent(nt_m)
if(d == 0) print('BOOM BOOM NO DIVERGENT CHAINS') else
print(paste('STOP DIVERGENCE PROBLEM: ', d, ' chains'))
```



#### Convergence and posterior predictions 


```{r}
dashboard(nt_m)
```


```{r}
precis(nt_m, 3)
```

```{r}
plot(nt_m)
```

```{r}
# funk::pairs2(extract.samples(nt_m)[c(2:8)])
```

```{r}
plot(precis(nt_m, 2), xlab='estimate, 89 CIs')
```
```{r}
traceplot(nt_m, pars=c('a', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8'))
```

```{r}
# sample y from posterior
y_post<-sim(nt_m)
focal$y_post<-apply(y_post, 2, mean)
ggplot(focal, aes(y_post, value, col=family)) + 
        geom_point() + 
        geom_abline(intercept=0, slope=1) +
        lims(y=c(min(focal$value), max(focal$value)),x=c(min(focal$value), max(focal$value))) +
        labs(x = 'Posterior mean', y = 'Observed', subtitle = nut)
```

```{r}
post<-extract.samples(nt_m)
mu <-post$a
ggplot(data.frame(x=exp(mu))) + 
            geom_density(aes(x), fill='grey') + 
            labs(x='mu', title=paste('Mean', nut, 'posterior')) +       
            geom_vline(xintercept=median(exp(mu)), col='red')

```
```{r}
post<-extract.samples(nt_m, pars=c( 'B8'))
# mu.coral <- post$B8[,1]
mu.ma <- post$B8
# hab<-data.frame(x = c(mu.coral, mu.ma), habitat = c(rep('Coral', 10500), rep('Macroalgae', 10500)))
ggplot() + 
            geom_density(aes(((mu.ma))),fill='grey', alpha=0.5) + 
          
            labs(x='mu', title='Mean selenium posterior') +       
            theme(legend.position = c(0.2, 0.5)) +
            geom_vline(xintercept=0, col='black')
            # geom_vline(xintercept=median((mu.coral)), col='black') +
            # geom_vline(xintercept=median((mu.ma)), col='black')

```

```{r}
pred<-expand.grid(species = unique(focal$species),
						  site = levels(focal$site)[2],
						  habitat_dummy=c(0,1))

	pred$trophic_level <-focal$trophic_level[match(pred$species, focal$species)]
	pred$Lmax <-focal$Lmax[match(pred$species, focal$species)]
	pred$K <-focal$K[match(pred$species, focal$species)]
	pred$tm <-focal$tm[match(pred$species, focal$species)]
	pred$benthic_pelagic_dummy <-focal$benthic_pelagic_dummy[match(pred$species,focal$species)]
	pred$family <-focal$family[match(pred$species, focal$species)]
	pred$habitat<-focal$habitat[match(pred$habitat_dummy, focal$habitat_dummy)]

	# replace varying intercept samples with zeros (SITE AND FAMILY)
	# 1000 samples by 21 sites
	a_site_zeros <- matrix(0,1000,uniques(focal$site))
	a_family_zeros <- matrix(0,1000,uniques(focal$family))
	meds<-link(nt_m, data=pred, n=1000, replace=list(X1=a_site_zeros, X2 = a_family_zeros))

	pred$mu<-apply(meds, 2, median)
	pred$lower95 <- apply( meds , 2 , HPDI , prob=0.95 )[1,]
	pred$upper95 <- apply( meds , 2 , HPDI , prob=0.95 )[2,]
	pred$lower50 <- apply( meds , 2 , HPDI , prob=0.50 )[1,]
	pred$upper50 <- apply( meds , 2 , HPDI , prob=0.50 )[2,]
	pred$nutrient<-nut
	mast<-pred

	## estimate average nutrient concentration irrespective of species
	base<-expand.grid(
	  						  family = unique(focal$family)[2],
						  site = levels(focal$site)[2], 
						  species=unique(focal$species)[1],
						  trophic_level = 0, 
						  Lmax = 0, 
						  K = 0, 
						  tm = 0, 
						  benthic_pelagic_dummy = 0,
						  habitat_dummy =1)
	# replace varying intercept samples with zeros (SITE AND FAMILY)
	meds<-link(nt_m, data=base, n=1000, replace=list(X1=a_site_zeros, X2 = a_family_zeros))

	base$mu<-apply(meds, 2, median)
	base$lower95 <- apply( meds , 2 , HPDI , prob=0.95 )[1,]
	base$upper95 <- apply( meds , 2 , HPDI , prob=0.95 )[2,]
	base$nutrient<-nut
	
# 	## transform mu
#     mast$mu<-exp(mast$mu)
#     mast$lower95<-exp(mast$lower95); mast$upper95<-exp(mast$upper95)
#     mast$lower50<-exp(mast$lower50); mast$upper50<-exp(mast$upper50)
#     base$mu<-exp(base$mu)
#     base$lower95<-exp(base$lower95); base$upper95<-exp(base$upper95)

```

```{r}
## plot species posterior predictions

stir<-stir.sub %>% filter(nutrient == nut)

## drop outliers
outlier.lims<-stir %>% group_by(nutrient) %>% summarise(out = 2*sd(value) + mean(value))
stir$lim<-outlier.lims$out[match(stir$nutrient, outlier.lims$nutrient)]
stir<-stir %>% filter(value <= lim)


## sort mast by FG
mast$FG<-stir$FG.fine[match(mast$species, stir$species)]
mast$species <-factor(mast$species, levels = rev(unique(mast$species[order(mast$FG)])))

cols<-data.frame(col=c('#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#a65628'),
    FG=c('Herbivore Scraper', 'Piscivore', 'Herbivore Browser','Herbivore Grazer', 'Invertivore & Piscivore', 'Invertivore'))
cols.named<-cols$col
names(cols.named)<-cols$FG

pos=position_dodge(width=0.5)

ggplot(mast ) + 
	# geom_rect(data = base, aes(ymin = lower95, ymax = upper95, xmin = -Inf, xmax=Inf), fill='grey', alpha=0.2) +
	# geom_hline(data = base, aes(yintercept=mu), col='red') +
	geom_pointrange(
		aes(y = mu, x = species, ymin = lower95, ymax = upper95,col=habitat), position=pos) +
	geom_point(aes(y = mu, x = species,  col=habitat), size=2, position=pos) +
	geom_jitter(data = stir, aes(species, value, col=habitat), alpha=0.25, width=0.15, size=0.75) +
	labs(y = 'Mineral concentration (ug per 100g)', x ='') +
	# scale_colour_manual(values = cols.named) +
	facet_wrap(~nutrient, nrow=1, scales='free_x') + 
	coord_flip() + 
	# guides(colour=FALSE) + 
	theme(axis.text.y=element_text(size=10, colour='black'),
		legend.position = 'top',
		legend.title = element_blank(),
			axis.text.x=element_text(size=10, colour='black'),
				axis.line = element_line(colour = "black"), 
				strip.text = element_text(face="bold", colour='black', size=10))

```

```{r}
## save model output
# save posterior preds
post<-as.data.frame(extract.samples(nt_m)) %>% gather(param, dist) %>% 
		filter(param %in% c('a', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8')) %>% mutate(nutrient = nut)

## bind and save as Rdata	
output<-list(nt_m, post, focal)


save(output, file = paste0('results/final/',
	 nut, '_scaled_habitat', '.Rdata'))
```

